### ISSUE TITLE
Cannot find module 'geotiff/dist/compression'. Possible incorrect path. 

### ISSUE THREAD

**Issue by jwoodmansey** [GeoTIFF/geotiff-stats#2]
Thanks for your work on this, this module has saved me a lot of work in a project! 

I'm not sure the require path is correct in `index.js`

Changing `const { getDecoder } = require('geotiff/dist/compression');` to `const { getDecoder } = require('geotiff');` works for me.

**Comment by DanielJDufour** [comment]
Thanks @jwoodmansey .  Glad to hear this helped!  I'll submit a fix as you suggested and republish within 24 hours.  (There's a couple other testing issues I have to resolve as well).  Thanks again!

**Comment by DanielJDufour** [comment]
New version is published:
https://www.npmjs.com/package/geotiff-stats

Thanks for your help @jwoodmansey !

**Comment by jwoodmansey** [comment]
Cheers @DanielJDufour this works for me now :)
